/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9xBNcjy2TMd
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useEffect, useState } from "react"
import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover";
import { Button } from "@/components/ui/button"
import { fetchNotifs } from "@/app/actions/notifications";
import { Check, MessageCircle } from 'lucide-react'
import { cn } from "@/lib/utils";
import { useRouter, usePathname } from "next/navigation";
import { BellIcon, GetIcon } from "./IconNotif";

export function MsgNotif({ socket }) {
    const router = useRouter()
    const [isOpen, setIsOpen] = useState(false)
    const [isMounted, setIsMounted] = useState(false);
    const [notifications, setNotifications] = useState([]);
    const unreadCount = notifications.filter(n => !n.IsRead && n.Type == "msg").length
   
    useEffect(() => {
        setIsMounted(true);
        fetchNotifs(setNotifications);
    }, []);
    const pathname = usePathname();
    const toggleDropdown = () => {
        setIsOpen(true)
    }
    const getAllMsg = () => {
        if (isMounted) {
            router.push("/")
        }
    }

    console.log(pathname);

    const markAsRead = (id) => {

        const Message = {
            Type: "notifications",
            ReceiverId: id,
            SubType: "read"
        }

        if (socket && socket.readyState === WebSocket.OPEN) {
            console.log("readddddddddd");

            socket.send(JSON.stringify(Message))
        }
        setNotifications(notifications.map(n => n.Id === id ? { ...n, IsRead: true } : n))

    }

    return (

        (<Popover>
            <PopoverTrigger asChild>
                <Button variant="ghost" size="icon" className="relative" onClick={toggleDropdown}>
                    <MessageCircle className={cn("h-6 w-6 text-muted-foreground", { 'animate-bounce': unreadCount > 0 })} />
                    {unreadCount > 0 && <span
                        className="absolute -top-1 -right-1 bg-red-500 text-white rounded-full px-1.5 py-0.5 text-xs font-medium">
                        {unreadCount}
                    </span>}
                </Button>
            </PopoverTrigger>
            {isOpen && (
                <PopoverContent align="end" className="w-80 p-4 rounded-lg shadow-lg" >
                    <div className="text-lg font-semibold">Notifications</div>
                    <div />
                    {notifications.map((n) => ((n.Type == "msg") && (
                        <div className="space-y-4 mb-2" key={n.Id}>
                            <div className="flex items-start gap-3">
                                <GetIcon type={n.Type} className="h-5 w-5" />
                                <div className="text-sm">
                                    <p className="font-medium">{"New message from @" + (n.SenderInfo.Email)} </p>
                                    <p className="text-sm text-muted-foreground">Hey, I just wanted to say hi and see how you're doing {n.Type}.</p>
                                    <p className="text-xs text-muted-foreground">{n.CreateAt.slice(0, 10) + "----/----" + n.CreateAt.slice(11).slice(0, 8)}</p>
                                    {(pathname == "/") && (<div className="flex gap-2 mt-2">
                                        <Button variant="outline" size="sm" onClick={() => markAsRead(n.Id)}>
                                            View
                                        </Button>
                                    </div>)}
                                </div>
                            </div>
                        </div>
                    )))}
                    <div className="text-center">
                        <Button variant="link" className="text-primary" onClick={getAllMsg}>
                            View all messages
                        </Button>
                    </div>
                </PopoverContent>
            )}
        </Popover>)
    );
}


