/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9xBNcjy2TMd
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useEffect, useState } from "react"
import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover";
import { Button } from "@/components/ui/button"
import { fetchNotifs, OnMessage } from "@/app/actions/notifications";
import { Check, MessageCircle } from 'lucide-react'
import { cn } from "@/lib/utils";
import { useRouter, usePathname } from "next/navigation";
import { BellIcon, GetIcon } from "./IconNotif";
import { socketGlobal } from "@/app/page";

export let setMsgNotif
export function MsgNotif({ socket }) {
    const router = useRouter()
    const [isOpen, setIsOpen] = useState(false)
    const [isMounted, setIsMounted] = useState(false);
    const [notifications, setNotifications] = useState([]);


    setMsgNotif = setNotifications
    useEffect(() => {
        setIsMounted(true);
        fetchNotifs(setNotifications, "msg");
    }, []);
    // console.log(socket);
    const unreadCount = notifications.length
    const pathname = usePathname();

    const toggleDropdown = () => {
        setIsOpen(true)
    }


    console.log(pathname);

    const markAsRead = (id) => {
        console.log(id);

        if (socket && socket.readyState === WebSocket.OPEN) {
            console.log("redddd");
            
            const Message = {
                Type: "notifications",
                ReceiverId: id,
                SubType: "read"
            }
            socket.send(JSON.stringify(Message))

        }
        fetchNotifs(setNotifications, "msg");
    }


    return (

        (<Popover>
            <PopoverTrigger asChild>
                <Button variant="ghost" size="icon" className="relative" onClick={toggleDropdown}>
                    <MessageCircle className={cn("h-6 w-6 text-muted-foreground", { 'animate-bounce': unreadCount > 0 })} />
                    {unreadCount > 0 && <span
                        className="absolute -top-1 -right-1 bg-red-500 text-white rounded-full px-1.5 py-0.5 text-xs font-medium">
                        {unreadCount}
                    </span>}
                </Button>
            </PopoverTrigger>
            {isOpen && (
                <PopoverContent align="end" className="w-80 p-4 rounded-lg shadow-lg" >
                    <div className="text-lg font-semibold">Notifications</div>
                    <div />
                    {notifications.map((n) => (!n.IsRead && (
                        <div className="space-y-4 mb-2" key={n.Id}>
                            <div className="flex items-start gap-3">
                                <GetIcon type={n.Type} className="h-5 w-5" />
                                <div className="text-sm">
                                    <p className="font-medium">{"New message from @" + (n.SenderInfo.Email)} </p>
                                    <p className="text-sm text-muted-foreground">{n.Message}.</p>
                                    <p className="text-xs text-muted-foreground">{n.Formated_date}</p>
                                </div>
                                {(<div className="flex items-center space-x-2">

                                    <Button size="icon" variant="ghost" onClick={() => markAsRead(n.Id)}>
                                        <Check className="h-4 w-4" />
                                        <span className="sr-only">Marquer comme lu</span>
                                    </Button>

                                </div>)}
                            </div>
                        </div>
                    )))}
                </PopoverContent>
            )}
        </Popover>)
    );
}


