/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9xBNcjy2TMd
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useEffect, useState } from "react"
import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover";
import { Button } from "@/components/ui/button"
import { fetchNotifs } from "@/app/actions/notifications";
export function Notifications() {
    const [isOpen, setIsOpen] = useState(false)
    const [Len, setLen] = useState(0)
    const [notifications, setNotifications] = useState([]);
    useEffect(() => {
        fetchNotifs(setLen, setNotifications);
    }, []);

    const toggleDropdown = () => {
        setIsOpen(true)
    }

    return (
        (<Popover>
            <PopoverTrigger asChild>
                <Button variant="ghost" size="icon" className="relative" onClick={toggleDropdown}>
                    <BellIcon className="h-6 w-6 text-muted-foreground animate-bounce" />
                    {Len > 0 && <span
                        className="absolute -top-1 -right-1 bg-red-500 text-white rounded-full px-1.5 py-0.5 text-xs font-medium">
                        {Len}
                    </span>}
                </Button>
            </PopoverTrigger>
            {isOpen && (
                <PopoverContent align="end" className="w-80 p-4 rounded-lg shadow-lg" >
                    <div className="text-lg font-semibold">Notifications</div>
                    <div />
                    {notifications.map((n) => (
                        <div className="space-y-4 mb-2" key={n.Id}>
                            <div className="flex items-start gap-3">
                                <IconNotif type={n.Type} className="h-5 w-5" />
                                <div>
                                    <p className="font-medium">{n.Message}</p>
                                    <p className="text-sm text-muted-foreground">Hey, I just wanted to say hi and see how you're doing {n.Type}.</p>
                                    <p className="text-xs text-muted-foreground">{n.CreateAt}</p>
                                    {(n.Type == "follow" || n.Type == "invitation") && (<div className="flex gap-2 mt-2">
                                        <Button variant="outline" size="sm" id={n.Id}>
                                            Accept
                                        </Button>
                                        <Button variant="outline" size="sm" id={n.Id}>
                                            Decline
                                        </Button>
                                    </div>)}
                                </div>
                            </div>
                        </div>
                    ))}
                    <div className="text-center">
                        <Button variant="link" className="text-primary">
                            View all notifications
                        </Button>
                    </div>
                </PopoverContent>
            )}
        </Popover>)
    );
}
function IconNotif({ type, ...props }) {
    switch (type) {
        case "follow"://color-blue
            return UserPlusIcon(props)
            break
        case "msg"://color-red
            return MessageCircleIcon(props)
            break
        case "event"://color-yellow
            return CalendarIcon(props)
            break
        case "invitation"://color-
            return UsersIcon(props)
            break

    }
}
function BellIcon(props) {
    return (
        (<svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round">
            <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
            <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
        </svg>)
    );
}


function CalendarIcon(props) {
    return (
        (<div className="flex-shrink-0 rounded-full bg-yellow-500 p-2 text-white">
            <svg
                {...props}
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round">
                <path d="M8 2v4" />
                <path d="M16 2v4" />
                <rect width="18" height="18" x="3" y="4" rx="2" />
                <path d="M3 10h18" />
            </svg>
        </div>)
    );
}
function UserPlusIcon(props) {
    return (
        (<div className="flex-shrink-0 rounded-full bg-red-500 p-2 text-white">
            <svg
                {...props}
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
            >
                <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
                <circle cx="9" cy="7" r="4" />
                <line x1="19" x2="19" y1="8" y2="14" />
                <line x1="22" x2="16" y1="11" y2="11" />
            </svg>
        </div>)
    )
}
function UsersIcon(props) {
    return (
        (<div className="flex-shrink-0 rounded-full bg-red-500 p-2 text-white">
            <svg
                {...props}
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
            >
                <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
                <circle cx="9" cy="7" r="4" />
                <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
                <path d="M16 3.13a4 4 0 0 1 0 7.75" />
            </svg>
        </div>)
    )
}
function MessageCircleIcon(props) {
    return (
        (<div className="flex-shrink-0 rounded-full bg-blue-500 p-2 text-white">
            <svg
                {...props}
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round">
                <path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z" />
            </svg>
        </div>)
    );
}


function ThumbsUpIcon(props) {
    return (
        (<svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round">
            <path d="M7 10v12" />
            <path
                d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2h0a3.13 3.13 0 0 1 3 3.88Z" />
        </svg>)
    );
}
