/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9xBNcjy2TMd
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useEffect, useState } from "react"
import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover";
import { Button } from "@/components/ui/button"
import { fetchNotifs } from "@/app/actions/notifications";
import { cn } from "@/lib/utils";
import { useRouter } from "next/navigation";
import { BellIcon, IconNotif } from "./IconNotif";

export function Notifications({ socket }) {
    const router = useRouter()
    const [isOpen, setIsOpen] = useState(false)
    const [isMounted, setIsMounted] = useState(false);
    const [Len, setLen] = useState(0)
    const [notifications, setNotifications] = useState([]);

    useEffect(() => {
        setIsMounted(true);
        fetchNotifs(setLen, setNotifications);
    }, []);

    const toggleDropdown = () => {
        setIsOpen(true)
    }
    const DisplayAllNotifs = () => {
        if (isMounted) {
            router.push("/notifications")
        }
    }

    return (

        (<Popover>
            <PopoverTrigger asChild>
                <Button variant="ghost" size="icon" className="relative" onClick={toggleDropdown}>
                    <BellIcon className={cn("h-6 w-6 text-muted-foreground", { 'animate-bounce': Len > 0 })} />
                    {Len > 0 && <span
                        className="absolute -top-1 -right-1 bg-red-500 text-white rounded-full px-1.5 py-0.5 text-xs font-medium">
                        {Len}
                    </span>}
                </Button>
            </PopoverTrigger>
            {isOpen && (
                <PopoverContent align="end" className="w-80 p-4 rounded-lg shadow-lg" >
                    <div className="text-lg font-semibold">Notifications</div>
                    <div />
                    {notifications.map((n) => (
                        <div className="space-y-4 mb-2" key={n.Id}>
                            <div className="flex items-start gap-3">
                                <IconNotif type={n.Type} className="h-5 w-5" />
                                <div>
                                    <p className="font-medium">{n.Message}</p>
                                    <p className="text-sm text-muted-foreground">Hey, I just wanted to say hi and see how you're doing {n.Type}.</p>
                                    <p className="text-xs text-muted-foreground">{n.CreateAt}</p>
                                    {(n.Type == "follow" || n.Type == "invitation") && (<div className="flex gap-2 mt-2">
                                        <Button variant="outline" size="sm" id={n.Id}>
                                            Accept
                                        </Button>
                                        <Button variant="outline" size="sm" id={n.Id}>
                                            Decline
                                        </Button>
                                    </div>)}
                                </div>
                            </div>
                        </div>
                    ))}
                    <div className="text-center">
                        <Button variant="link" className="text-primary" onClick={DisplayAllNotifs}>
                            View all notifications
                        </Button>
                    </div>
                </PopoverContent>
            )}
        </Popover>)
    );
}


