CREATE TABLE IF NOT EXISTS Chats (
    id TEXT PRIMARY KEY,
    senderId TEXT NOT NULL,
    receverId TEXT NOT NULL,
    content TEXT NOT NULL,
    sendAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (senderId) REFERENCES Users(id),
    FOREIGN KEY (receverId) REFERENCES Users(id)
);
