CREATE TABLE IF NOT EXISTS LikesDislikes (
    id TEXT PRIMARY KEY,
    postId INTEGER,
    userId INTEGER,
    liked BOOLEAN NOT NULL DEFAULT FALSE,
    disliked BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (postid) REFERENCES Posts(id),
    FOREIGN KEY (userid) REFERENCES Users(id)
);
