CREATE TABLE IF NOT EXISTS Posts (
    id TEXT PRIMARY KEY,
    userId TEXT NOT NULL,
    content TEXT NOT NULL,
    imageUrl TEXT NOT NULL,
    creatdate DATETIME DEFAULT CURRENT_TIMESTAMP,
    statut TEXT NOT NULL,
    FOREIGN KEY (userId) REFERENCES Users(id)
);
