CREATE TABLE IF NOT EXISTS UserPost (
    id INTEGER PRIMARY KEY,
    postid INTEGER NOT NULL,
    userid INTEGER NOT NULL,
    FOREIGN KEY (postid) REFERENCES Posts(id),
    FOREIGN KEY (userid) REFERENCES Users(id)
);
